/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonRouteImport } from './routes/pokemon'
import { Route as AnchorRouteImport } from './routes/anchor'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as R3pokemonRouteRouteImport } from './routes/3pokemon.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PokemonIndexRouteImport } from './routes/pokemon/index'
import { Route as PostsChar123CategoryChar125RouteImport } from './routes/posts.{-$category}'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PokemonPokemonIdRouteImport } from './routes/pokemon/$pokemonId'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PokemonGenIndexRouteImport } from './routes/pokemon/gen/index'
import { Route as PokemonGenGenerationRouteImport } from './routes/pokemon/gen/$generation'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as PokemonGenGenerationPokemonIdRouteImport } from './routes/pokemon/gen_/$generation/$pokemonId'

const PokemonRoute = PokemonRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchorRoute = AnchorRouteImport.update({
  id: '/anchor',
  path: '/anchor',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const R3pokemonRouteRoute = R3pokemonRouteRouteImport.update({
  id: '/3pokemon',
  path: '/3pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PokemonRoute,
} as any)
const PostsChar123CategoryChar125Route =
  PostsChar123CategoryChar125RouteImport.update({
    id: '/{-$category}',
    path: '/{-$category}',
    getParentRoute: () => PostsRouteRoute,
  } as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PokemonPokemonIdRoute = PokemonPokemonIdRouteImport.update({
  id: '/$pokemonId',
  path: '/$pokemonId',
  getParentRoute: () => PokemonRoute,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PokemonGenIndexRoute = PokemonGenIndexRouteImport.update({
  id: '/gen/',
  path: '/gen/',
  getParentRoute: () => PokemonRoute,
} as any)
const PokemonGenGenerationRoute = PokemonGenGenerationRouteImport.update({
  id: '/gen/$generation',
  path: '/gen/$generation',
  getParentRoute: () => PokemonRoute,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PokemonGenGenerationPokemonIdRoute =
  PokemonGenGenerationPokemonIdRouteImport.update({
    id: '/gen_/$generation/$pokemonId',
    path: '/gen/$generation/$pokemonId',
    getParentRoute: () => PokemonRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3pokemon': typeof R3pokemonRouteRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/pokemon': typeof PokemonRouteWithChildren
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/{-$category}': typeof PostsChar123CategoryChar125Route
  '/pokemon/': typeof PokemonIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/pokemon/gen/$generation': typeof PokemonGenGenerationRoute
  '/pokemon/gen': typeof PokemonGenIndexRoute
  '/pokemon/gen/$generation/$pokemonId': typeof PokemonGenGenerationPokemonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3pokemon': typeof R3pokemonRouteRoute
  '/anchor': typeof AnchorRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/{-$category}': typeof PostsChar123CategoryChar125Route
  '/pokemon': typeof PokemonIndexRoute
  '/posts': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/pokemon/gen/$generation': typeof PokemonGenGenerationRoute
  '/pokemon/gen': typeof PokemonGenIndexRoute
  '/pokemon/gen/$generation/$pokemonId': typeof PokemonGenGenerationPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3pokemon': typeof R3pokemonRouteRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/pokemon': typeof PokemonRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/{-$category}': typeof PostsChar123CategoryChar125Route
  '/pokemon/': typeof PokemonIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/pokemon/gen/$generation': typeof PokemonGenGenerationRoute
  '/pokemon/gen/': typeof PokemonGenIndexRoute
  '/pokemon/gen_/$generation/$pokemonId': typeof PokemonGenGenerationPokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3pokemon'
    | '/posts'
    | '/anchor'
    | '/pokemon'
    | '/pokemon/$pokemonId'
    | '/posts/$postId'
    | '/posts/{-$category}'
    | '/pokemon/'
    | '/posts/'
    | '/route-a'
    | '/route-b'
    | '/pokemon/gen/$generation'
    | '/pokemon/gen'
    | '/pokemon/gen/$generation/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3pokemon'
    | '/anchor'
    | '/pokemon/$pokemonId'
    | '/posts/$postId'
    | '/posts/{-$category}'
    | '/pokemon'
    | '/posts'
    | '/route-a'
    | '/route-b'
    | '/pokemon/gen/$generation'
    | '/pokemon/gen'
    | '/pokemon/gen/$generation/$pokemonId'
  id:
    | '__root__'
    | '/'
    | '/3pokemon'
    | '/posts'
    | '/_pathlessLayout'
    | '/anchor'
    | '/pokemon'
    | '/_pathlessLayout/_nested-layout'
    | '/pokemon/$pokemonId'
    | '/posts/$postId'
    | '/posts/{-$category}'
    | '/pokemon/'
    | '/posts/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/pokemon/gen/$generation'
    | '/pokemon/gen/'
    | '/pokemon/gen_/$generation/$pokemonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3pokemonRouteRoute: typeof R3pokemonRouteRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AnchorRoute: typeof AnchorRoute
  PokemonRoute: typeof PokemonRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon': {
      id: '/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchor': {
      id: '/anchor'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3pokemon': {
      id: '/3pokemon'
      path: '/3pokemon'
      fullPath: '/3pokemon'
      preLoaderRoute: typeof R3pokemonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof PokemonRoute
    }
    '/posts/{-$category}': {
      id: '/posts/{-$category}'
      path: '/{-$category}'
      fullPath: '/posts/{-$category}'
      preLoaderRoute: typeof PostsChar123CategoryChar125RouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/pokemon/$pokemonId': {
      id: '/pokemon/$pokemonId'
      path: '/$pokemonId'
      fullPath: '/pokemon/$pokemonId'
      preLoaderRoute: typeof PokemonPokemonIdRouteImport
      parentRoute: typeof PokemonRoute
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/pokemon/gen/': {
      id: '/pokemon/gen/'
      path: '/gen'
      fullPath: '/pokemon/gen'
      preLoaderRoute: typeof PokemonGenIndexRouteImport
      parentRoute: typeof PokemonRoute
    }
    '/pokemon/gen/$generation': {
      id: '/pokemon/gen/$generation'
      path: '/gen/$generation'
      fullPath: '/pokemon/gen/$generation'
      preLoaderRoute: typeof PokemonGenGenerationRouteImport
      parentRoute: typeof PokemonRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/pokemon/gen_/$generation/$pokemonId': {
      id: '/pokemon/gen_/$generation/$pokemonId'
      path: '/gen/$generation/$pokemonId'
      fullPath: '/pokemon/gen/$generation/$pokemonId'
      preLoaderRoute: typeof PokemonGenGenerationPokemonIdRouteImport
      parentRoute: typeof PokemonRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsChar123CategoryChar125Route: typeof PostsChar123CategoryChar125Route
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsChar123CategoryChar125Route: PostsChar123CategoryChar125Route,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PokemonRouteChildren {
  PokemonPokemonIdRoute: typeof PokemonPokemonIdRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  PokemonGenGenerationRoute: typeof PokemonGenGenerationRoute
  PokemonGenIndexRoute: typeof PokemonGenIndexRoute
  PokemonGenGenerationPokemonIdRoute: typeof PokemonGenGenerationPokemonIdRoute
}

const PokemonRouteChildren: PokemonRouteChildren = {
  PokemonPokemonIdRoute: PokemonPokemonIdRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  PokemonGenGenerationRoute: PokemonGenGenerationRoute,
  PokemonGenIndexRoute: PokemonGenIndexRoute,
  PokemonGenGenerationPokemonIdRoute: PokemonGenGenerationPokemonIdRoute,
}

const PokemonRouteWithChildren =
  PokemonRoute._addFileChildren(PokemonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3pokemonRouteRoute: R3pokemonRouteRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AnchorRoute: AnchorRoute,
  PokemonRoute: PokemonRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
